field: e16e9bb3-a163-4ea0-92ea-a800d1fdff70
fieldLayouts:
  36a3a0fb-78c9-49e0-9df0-597d49379a2f:
    tabs:
      -
        elements:
          -
            fieldUid: 2b77b054-c737-4004-bc7d-b038156c3c12
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 93d431b2-ea63-4e49-9ef8-e071026132c9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2b77b054-c737-4004-bc7d-b038156c3c12:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  93d431b2-ea63-4e49-9ef8-e071026132c9:
    contentColumnType: boolean
    fieldGroup: null
    handle: showThis
    instructions: ''
    name: 'Show This?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: anotherBlockType
name: 'Another Block Type'
sortOrder: 2
